### ISSUE TITLE
Use id instead of class

### ISSUE THREAD

**Issue by gdedi001** [mdkarr01/prj-rev-bwfs-dasmoto#2]
In this situation use `id` instead of `class`. Read the summary for more info..

https://github.com/mdkarr01/prj-rev-bwfs-dasmoto/blob/master/dasmoto/index.html#L9
https://github.com/mdkarr01/prj-rev-bwfs-dasmoto/blob/master/dasmoto/index.html#L13

**Comment by mdkarr01** [comment]
Great point. I hadn't considered ID in those instances but it makes perfect sense.
